[package]
name = "fee-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
futures = "0.3.31"
solana-client = "2.2.0"
solana-sdk = "2.2.1"
solana-transaction-status = "2.2.0"
solana-rpc-client-api = "2.2.0"
tokio = { version = "1.43.0", features = ["full"] }
